### ISSUE TITLE
Ororo Error

### ISSUE THREAD

**Issue by thejason40** [Buksa/plugins_for_showtime#11]
When using movian on ps3 I've noticed an error with ororo. Once I have loaded an episode of any tv show, I can't then open the episode list of any show again until I reset movian. 
I am using ororo plugin 0.77 and movian 4.99.672. Here is my system log:  http://sprunge.us/cRGe

**Comment by Buksa** [comment]
fixed in 0.7.8

**Comment by thejason40** [comment]
Updated to 0.7.8  and it's still giving the error. Here's a new log: http://sprunge.us/cgOH

**Comment by Buksa** [comment]
work fine for me at least on linux 4.99.672.g2680b and Nacl

**Comment by Buksa** [comment]
disable thetvdb in plugin settings anyway it doesn't work properly
