### ISSUE TITLE
showtime ororo netherlands

### ISSUE THREAD

**Issue by troathscream** [Buksa/plugins_for_showtime#5]
Hi Buksa,
there is a problem with ororo.tv in the netherlands. somehow it gets blocked and i get a http failure in showtime or page not found in the browser. I found that when i type http://ororo.tv/nl in my browser suddenly i can login again and browse and watch series. Is there a way to modify this in a file or script for use with showtime on the ps3 so i can watch series again?

Tnx and Grtz

Troathscream

**Comment by Buksa** [comment]
try 0.6

**Comment by leonvisser75** [comment]
Now there is an other problem,
Unable to open resource
Http request failed http://ororo.tv/users/sign_in -- HTTP error: 404

**Comment by troathscream** [comment]
Yep, i have the same error. If i use my browser an go to ororo.tv/en i get the error : the page you were looking for doesn't exist. If go to ororo.tv/nl it works.

--- Oorspronkelijk bericht ---

Van: "leonvisser75" <notifications@github.com>
Verzonden: 30 januari 2015 10:35
Aan: "Buksa/plugins_for_showtime" <plugins_for_showtime@noreply.github.com>
CC: "troathscream" <troathscream@hotmail.com>
Onderwerp: Re: [plugins_for_showtime] showtime ororo netherlands (#5)

Now there is an other problem,
Unable to open resource
Http request failed http://ororo.tv/users/sign_in -- HTTP error: 404

---

**Comment by Buksa** [comment]
try 0.7.1 
just change geoUrl in settings

**Comment by troathscream** [comment]
hi Buksa, stil the same http error. changed geoURL to ororo.tv/nl sadly the same result. using movian bleeding edge 4.9.507

**Comment by Buksa** [comment]
turn on debug in settings and send me log

**Comment by troathscream** [comment]
hi, i couldnt find the debug log, so i just shot a picture of the on screen log.

--- Oorspronkelijk bericht ---

Van: "Buksa" <notifications@github.com>
Verzonden: 3 juni 2015 19:45
Aan: "Buksa/plugins_for_showtime" <plugins_for_showtime@noreply.github.com>
CC: "troathscream" <troathscream@hotmail.com>
Onderwerp: Re: [plugins_for_showtime] showtime ororo netherlands (#5)

turn on debug in settings and send me log

On Wed, Jun 3, 2015 at 12:50 AM, troathscream <notifications@github.com>
wrote:

> hi Buksa, stil the same http error. changed geoURL to ororo.tv/nl sadly
> the same result. using movian bleeding edge 4.9.507
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Buksa/plugins_for_showtime/issues/5#issuecomment-108234906>
> .
>


---

**Comment by troathscream** [comment]
sorry forgot the picture,
attached now.

grtz

--- Oorspronkelijk bericht ---

Van: "Buksa" <notifications@github.com>
Verzonden: 3 juni 2015 19:45
Aan: "Buksa/plugins_for_showtime" <plugins_for_showtime@noreply.github.com>
CC: "troathscream" <troathscream@hotmail.com>
Onderwerp: Re: [plugins_for_showtime] showtime ororo netherlands (#5)

turn on debug in settings and send me log

On Wed, Jun 3, 2015 at 12:50 AM, troathscream <notifications@github.com>
wrote:

> hi Buksa, stil the same http error. changed geoURL to ororo.tv/nl sadly
> the same result. using movian bleeding edge 4.9.507
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Buksa/plugins_for_showtime/issues/5#issuecomment-108234906>
> .
>


---

**Comment by Buksa** [comment]
i need good socks5 nl proxy :) i will check

**Comment by Buksa** [comment]
check 0.7.3 try http://ororo.tv/nl then http://ororo.tv/en
if get same problem 
find proxy for me :)

**Comment by troathscream** [comment]
Hi Buksa,

it seems that ororo is geoblocked in the netherlands,
i have the same problem on KODI and XBMC as i have on the PS3.
I checked version 0.7.3 and tried both ororo.tv/nl and ororo.tv/en
still the same.

I googled for Free anonymous Socks5 proxies, here are the results

We found 3 proxies for country: Netherlands > Protocol: socks5 > Anonymity: all    














    
    
         IP address
        Port
        Protocol
        Country
        Region
        City
        Anonymity
        Speed
        Uptime
        Response
        Last checked


    
    

    
	
	


	

	
	
	
				 82.73.62.145

						31563
		SOCKS5
		 Netherlands
		Friesland
		Sneek
		High anonymity
		  45 kB/s 
		57.1%
		13233 ms   
                                				5 hours ago



	


	

	
	
	
				 178.85.27.249

						48703
		SOCKS5
		 Netherlands
		Gelderland
		Nijmegen
		High anonymity
		 

		70%
		26446 ms   
                                				7 hours ago



	


	

	
	
	
				 37.46.124.69

						1080
		SOCKS5
		 Netherlands
		

		

		High anonymity
		 

		47.2%
		13680 ms   
                                				5 hours ago
Date: Thu, 4 Jun 2015 20:20:22 -0700

**Comment by Buksa** [comment]
ok try this 
locate the 'httpcookies' file in /dev_hdd0/game/HTSS00003/USRDIR/st4_settings/settings and make a backup (just in case).
and add 	
[code]
{
		"name": "nl",
		"path": "/",
		"domain": "ororo.tv",
		"value": "true",
		"expire": 2064848289
	},
[/code]
after [
exemple http://pastebin.com/zSkwq9Xn

**Comment by troathscream** [comment]
pasted into httpcookies,
sadly still doesnt work,
also tried changing the geosettings after altering the httpcookies file but didnt work also.

Date: Sun, 7 Jun 2015 10:14:27 -0700

**Comment by troathscream** [comment]
hi Buksa, with your last update your ororo plugin works again :) , tnx for that. only thing i noticed is that array view has to be disabled or the screen stays empty, when disabled you can browse  tv shows, but movies gives you a http error 404. Just wanted to let you know that i'm happy ot is working again!
