### ISSUE TITLE
Ororo sorting

### ISSUE THREAD

**Issue by issame** [Buksa/plugins_for_showtime#7]
Ororo sorting is not working at all

**Comment by thejason40** [comment]
I've noticed this too. It used to sort by recently added but that option seems to have disappeared.

**Comment by Buksa** [comment]
fixed in 0.5.11

**Comment by thejason40** [comment]
I know I'm being a pain but can it order by lastupdated, rather than newest? Newest orders by when the series as a whole was added, lastupdated orders by when the last episode was added.

**Comment by Buksa** [comment]
done in 0.6.1 
movian must be 4.9+
